server:
 port: 8081
 servlet:
  context-path: /api	
spring:
 jpa:
  hibernate:
   ddl-auto: create
 datasource:
  url: jdbc:mysql://localhost:3306/financescontrollDB
  username: felipe
  password: senha123
  driver-class-name: com.mysql.cj.jdbc.Driver