server:
 port: 8081
 servlet:
  context-path: /api	
spring:
 datasource-fc:
  url: jdbc:mysql://localhost:3306/financescontrollDB
  username: felipe
  password: senha123
  driver-class-name: com.mysql.cj.jdbc.Driver
 datasource-oauth:
  url: jdbc:mysql://localhost:3306/oauth
  username: fc_oauth
  password: senha123
  driver-class-name: com.mysql.cj.jdbc.Driver